const mongoose = require("mongoose");
const User = require("../models/user"); // Adjust the path as necessary
const logger = require('../utils/logger')("userSeeder"); // Import your logger
const { userValidate } = require("../schemas/userSchema");
const users = [
  {
    username: "priya_m",
    email: "priya@domain.com",
    phone: "+919988776655",
    dob: "1990-05-15",
    city: "Mumbai",
    country: "India",
    graduationYear: 2012,
    degree: "MBA",
    department: "Marketing",
    employer: "BrandX",
    jobTitle: "Brand Manager",
    industry: "Marketing",
    experience: 8,
    skills: ["Marketing Strategy", "Campaign Management"],
    projects: ["Campaign X", "Campaign L"],
    achievements: ["Top Brand Manager"],
    linkedin: "https://www.linkedin.com/in/priya",
    github: "https://github.com/priya",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    discussionPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 170,
    isStarAlumni: true,
    password: "priYa2024!$",
  },
  // existing users here...
  {
    username: "n",
    email: "rahul@domain.com",
    phone: "+919876543210",
    dob: "1986-11-30",
    city: "Noida",
    country: "India",
    graduationYear: 2008,
    degree: "B.Tech",
    department: "Mechanical Engineering",
    employer: "MechSolutions",
    jobTitle: "Mechanical Engineer",
    industry: "Engineering",
    experience: 16,
    skills: ["CAD", "Thermodynamics", "Fluid Mechanics"],
    projects: ["Project M1", "Project M2"],
    achievements: ["Best Mechanical Engineer"],
    linkedin: "https://www.linkedin.com/in/ravi",
    github: "https://github.com/ravi",
    profilePicture: "https://example.com/images/ravi.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 210,
    isStarAlumni: true,
    password: "raviSharma2024!$",
  },
  {
    username: "suman_k",
    email: "suman@domain.com",
    phone: "+919900112233",
    dob: "1993-07-18",
    city: "Kolkata",
    country: "India",
    graduationYear: 2015,
    degree: "M.Tech",
    department: "Information Technology",
    employer: "TechWorld",
    jobTitle: "System Analyst",
    industry: "IT",
    experience: 5,
    skills: ["System Analysis", "Data Modeling", "Software Testing"],
    projects: ["Project T1", "Project T2"],
    achievements: ["Employee of the Year"],
    linkedin: "https://www.linkedin.com/in/suman",
    github: "https://github.com/suman",
    profilePicture: "https://example.com/images/suman.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    discussionPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 150,
    isStarAlumni: false,
    password: "suman2024!$",
  },
  {
    username: "meera_s",
    email: "meera@domain.com",
    phone: "+919900445566",
    dob: "1994-03-10",
    city: "Chennai",
    country: "India",
    graduationYear: 2010,
    degree: "M.Sc",
    department: "Data Science",
    employer: "DataSolutions",
    jobTitle: "Data Scientist",
    industry: "Analytics",
    experience: 7,
    skills: ["Python", "R", "Machine Learning"],
    projects: ["Project X", "Project Y"],
    achievements: ["Published Paper in Data Science Journal"],
    linkedin: "https://www.linkedin.com/in/anjali",
    github: "https://github.com/anjali",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    discussionPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 160,
    isStarAlumni: true,
    password: "meera2024!$",
  },
  {
    username: "m",
    email: "vikram@domain.com",
    phone: "+917007007007",
    dob: "1992-10-30",
    city: "Ahmedabad",
    country: "India",
    graduationYear: 2014,
    degree: "MBA",
    department: "Marketing",
    employer: "MarketInc",
    jobTitle: "Marketing Manager",
    industry: "Marketing",
    experience: 6,
    skills: ["SEO", "Digital Marketing", "Content Strategy"],
    projects: ["Campaign A", "Campaign B"],
    achievements: ["Top Marketer of the Year"],
    linkedin: "https://www.linkedin.com/in/vikram",
    github: "https://github.com/vikram",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    discussionPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 180,
    isStarAlumni: false,
    password: "m", // Add password
  },
  {
    username: "neeraj_k",
    email: "neeraj@domain.com",
    phone: "+919988665544",
    dob: "1991-04-17",
    city: "Pune",
    country: "India",
    graduationYear: 2013,
    degree: "B.Sc",
    department: "Physics",
    employer: "ResearchCorp",
    jobTitle: "Research Scientist",
    industry: "Research",
    experience: 7,
    skills: ["Quantum Physics", "Experimental Design", "Data Analysis"],
    projects: ["Project R1", "Project R2"],
    achievements: ["Research Innovation Award"],
    linkedin: "https://www.linkedin.com/in/neeraj",
    github: "https://github.com/neeraj",
    profilePicture: "https://example.com/images/neeraj.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    discussionPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 170,
    isStarAlumni: true,
    password: "neeraj2024!$",
  },
  // Add additional 45 profiles following similar structure...
  {
    username: "anuj_singh",
    email: "anuj@domain.com",
    phone: "+919877112233",
    dob: "1995-09-12",
    city: "Bangalore",
    country: "India",
    graduationYear: 2017,
    degree: "M.Com",
    department: "Commerce",
    employer: "ComTech",
    jobTitle: "Finance Manager",
    industry: "Finance",
    experience: 3,
    skills: ["Investment Analysis", "Financial Planning"],
    projects: ["Project F1", "Project F2"],
    achievements: ["Young Finance Leader"],
    linkedin: "https://www.linkedin.com/in/anuj",
    github: "https://github.com/anuj",
    profilePicture: "https://example.com/images/anuj.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 120,
    isStarAlumni: false,
    password: "anuj2024!$",
  },
  {
    username: "kanika_s",
    email: "kanika@domain.com",
    phone: "+919900667788",
    dob: "1988-06-28",
    city: "Delhi",
    country: "India",
    graduationYear: 2010,
    degree: "MBA",
    department: "HR",
    employer: "PeopleWorks",
    jobTitle: "HR Manager",
    industry: "Human Resources",
    experience: 10,
    skills: ["Talent Acquisition", "HR Strategy"],
    projects: ["Project H1", "Project H2"],
    achievements: ["Top HR Manager"],
    linkedin: "https://www.linkedin.com/in/kanika",
    github: "https://github.com/kanika",
    profilePicture: "https://example.com/images/kanika.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 190,
    isStarAlumni: true,
    password: "kanika2024!$",
  },
  {
    username: "rajveer_g",
    email: "rajveer@domain.com",
    phone: "+919900554433",
    dob: "1992-02-20",
    city: "Jaipur",
    country: "India",
    graduationYear: 2014,
    degree: "B.Tech",
    department: "Civil Engineering",
    employer: "BuildSmart",
    jobTitle: "Site Engineer",
    industry: "Construction",
    experience: 6,
    skills: ["Site Management", "Structural Analysis"],
    projects: ["Project B1", "Project B2"],
    achievements: ["Best Site Engineer"],
    linkedin: "https://www.linkedin.com/in/rajveer",
    github: "https://github.com/rajveer",
    profilePicture: "https://example.com/images/rajveer.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 160,
    isStarAlumni: false,
    password: "rajveer2024!$",
  },
  // Add more users similarly...
  {
    username: "isha_k",
    email: "isha@domain.com",
    phone: "+919900443322",
    dob: "1995-12-05",
    city: "Chandigarh",
    country: "India",
    graduationYear: 2017,
    degree: "M.Sc",
    department: "Biotechnology",
    employer: "BioTech Labs",
    jobTitle: "Biotech Researcher",
    industry: "Biotechnology",
    experience: 3,
    skills: ["Biotech Research", "Genetics"],
    projects: ["Project BT1", "Project BT2"],
    achievements: ["Research Excellence Award"],
    linkedin: "https://www.linkedin.com/in/isha",
    github: "https://github.com/isha",
    profilePicture: "https://example.com/images/isha.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 130,
    isStarAlumni: false,
    password: "isha2024!$",
  },
  {
    username: "dinesh_m",
    email: "dinesh@domain.com",
    phone: "+919900998877",
    dob: "1984-01-23",
    city: "Bhopal",
    country: "India",
    graduationYear: 2006,
    degree: "B.E.",
    department: "Electrical Engineering",
    employer: "PowerGrid Corp",
    jobTitle: "Electrical Engineer",
    industry: "Energy",
    experience: 18,
    skills: ["Electrical Systems", "Power Distribution"],
    projects: ["Project E1", "Project E2"],
    achievements: ["Employee of the Month"],
    linkedin: "https://www.linkedin.com/in/dinesh",
    github: "https://github.com/dinesh",
    profilePicture: "https://example.com/images/dinesh.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 200,
    isStarAlumni: true,
    password: "dinesh2024!$",
  },
  {
    username: "swati_r",
    email: "swati@domain.com",
    phone: "+919988221122",
    dob: "1990-06-05",
    city: "Lucknow",
    country: "India",
    graduationYear: 2012,
    degree: "M.Tech",
    department: "Software Engineering",
    employer: "SoftSolutions",
    jobTitle: "Software Developer",
    industry: "IT",
    experience: 8,
    skills: ["Java", "Python", "Software Development"],
    projects: ["Project S1", "Project S2"],
    achievements: ["Top Developer Award"],
    linkedin: "https://www.linkedin.com/in/swati",
    github: "https://github.com/swati",
    profilePicture: "https://example.com/images/swati.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 170,
    isStarAlumni: false,
    password: "swati2024!$",
  },
  {
    username: "vivek_p",
    email: "vivek@domain.com",
    phone: "+919999887766",
    dob: "1987-11-17",
    city: "Jaipur",
    country: "India",
    graduationYear: 2009,
    degree: "B.Sc",
    department: "Chemistry",
    employer: "ChemLab",
    jobTitle: "Lab Technician",
    industry: "Pharmaceuticals",
    experience: 15,
    skills: ["Lab Techniques", "Chemical Analysis"],
    projects: ["Project C1", "Project C2"],
    achievements: ["Lab Excellence Award"],
    linkedin: "https://www.linkedin.com/in/vivek",
    github: "https://github.com/vivek",
    profilePicture: "https://example.com/images/vivek.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 190,
    isStarAlumni: true,
    password: "vivek2024!$",
  },
  {
    username: "anita_j",
    email: "anita@domain.com",
    phone: "+919900776655",
    dob: "1993-07-30",
    city: "Coimbatore",
    country: "India",
    graduationYear: 2015,
    degree: "B.Tech",
    department: "Information Technology",
    employer: "TechnoBytes",
    jobTitle: "IT Consultant",
    industry: "IT",
    experience: 5,
    skills: ["Consulting", "Project Management"],
    projects: ["Project I1", "Project I2"],
    achievements: ["Consultant of the Year"],
    linkedin: "https://www.linkedin.com/in/anita",
    github: "https://github.com/anita",
    profilePicture: "https://example.com/images/anita.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 150,
    isStarAlumni: false,
    password: "anita2024!$",
  },
  {
    username: "nisha_p",
    email: "nisha@domain.com",
    phone: "+919900554433",
    dob: "1990-10-10",
    city: "Ahmedabad",
    country: "India",
    graduationYear: 2012,
    degree: "MBA",
    department: "Finance",
    employer: "FinServe",
    jobTitle: "Financial Analyst",
    industry: "Finance",
    experience: 9,
    skills: ["Financial Analysis", "Investment Strategies"],
    projects: ["Project F3", "Project F4"],
    achievements: ["Financial Analyst of the Year"],
    linkedin: "https://www.linkedin.com/in/nisha",
    github: "https://github.com/nisha",
    profilePicture: "https://example.com/images/nisha.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 180,
    isStarAlumni: true,
    password: "nisha2024!$",
  },
  {
    username: "ajay_b",
    email: "ajay@domain.com",
    phone: "+919900112233",
    dob: "1994-04-12",
    city: "Patna",
    country: "India",
    graduationYear: 2016,
    degree: "BBA",
    department: "Business Administration",
    employer: "BizCorp",
    jobTitle: "Marketing Executive",
    industry: "Marketing",
    experience: 4,
    skills: ["Market Research", "Brand Development"],
    projects: ["Project B3", "Project B4"],
    achievements: ["Top Marketing Executive"],
    linkedin: "https://www.linkedin.com/in/ajay",
    github: "https://github.com/ajay",
    profilePicture: "https://example.com/images/ajay.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 140,
    isStarAlumni: false,
    password: "ajay2024!$",
  },
  {
    username: "mohit_g",
    email: "mohit@domain.com",
    phone: "+919988776655",
    dob: "1985-12-25",
    city: "Nashik",
    country: "India",
    graduationYear: 2007,
    degree: "M.Sc",
    department: "Mathematics",
    employer: "MathWorks",
    jobTitle: "Data Scientist",
    industry: "Data Science",
    experience: 17,
    skills: ["Data Analysis", "Machine Learning"],
    projects: ["Project D3", "Project D4"],
    achievements: ["Data Scientist of the Year"],
    linkedin: "https://www.linkedin.com/in/mohit",
    github: "https://github.com/mohit",
    profilePicture: "https://example.com/images/mohit.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 220,
    isStarAlumni: true,
    password: "mohit2024!$",
  },
  {
    username: "geeta_s",
    email: "geeta@domain.com",
    phone: "+919900223344",
    dob: "1991-05-14",
    city: "Gurgaon",
    country: "India",
    graduationYear: 2013,
    degree: "B.Com",
    department: "Commerce",
    employer: "Finwise",
    jobTitle: "Account Manager",
    industry: "Finance",
    experience: 7,
    skills: ["Account Management", "Client Relations"],
    projects: ["Project F5", "Project F6"],
    achievements: ["Top Account Manager"],
    linkedin: "https://www.linkedin.com/in/geeta",
    github: "https://github.com/geeta",
    profilePicture: "https://example.com/images/geeta.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 160,
    isStarAlumni: false,
    password: "geeta2024!$",
  },
  {
    username: "ravi_s",
    email: "ravi@domain.com",
    phone: "+919988667788",
    dob: "1988-02-10",
    city: "Indore",
    country: "India",
    graduationYear: 2010,
    degree: "M.Tech",
    department: "Electronics",
    employer: "ElectroTech",
    jobTitle: "Electronics Engineer",
    industry: "Electronics",
    experience: 14,
    skills: ["Circuit Design", "Embedded Systems"],
    projects: ["Project E3", "Project E4"],
    achievements: ["Best Electronics Engineer"],
    linkedin: "https://www.linkedin.com/in/ravi",
    github: "https://github.com/ravi",
    profilePicture: "https://example.com/images/ravi.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 190,
    isStarAlumni: true,
    password: "ravi2024!$",
  },
  {
    username: "sonia_k",
    email: "sonia@domain.com",
    phone: "+919900445566",
    dob: "1992-08-22",
    city: "Nagpur",
    country: "India",
    graduationYear: 2014,
    degree: "B.A.",
    department: "English Literature",
    employer: "EduWorld",
    jobTitle: "Content Writer",
    industry: "Education",
    experience: 6,
    skills: ["Content Creation", "Editing"],
    projects: ["Project C5", "Project C6"],
    achievements: ["Best Content Writer"],
    linkedin: "https://www.linkedin.com/in/sonia",
    github: "https://github.com/sonia",
    profilePicture: "https://example.com/images/sonia.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 160,
    isStarAlumni: false,
    password: "sonia2024!$",
  }
  
];


async function seedUsers() {
  try {
    for (let userData of users) {
      const { password, ...userDetails } = userData;
      const user = new User(userDetails);
      await User.register(user, password); // This hashes the password and saves the user
      logger.info(`User ${user.username} seeded successfully`);
    }
  } catch (error) {
    logger.error('Error seeding users:', error);
  }
}

module.exports = seedUsers;
