const jobs = [
  {
    title: "Frontend Developer",
    salary: 60000,
    location: "San Francisco, CA",
    jobType: "Full-time",
    companyName: "Tech Innovations Inc.",
    applyLink: "http://techinnovations.com/careers/frontend-developer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d0f",
    reports: [],
    likes: []
  },
  {
    title: "Data Scientist",
    salary: 80000,
    location: "New York, NY",
    jobType: "Full-time",
    companyName: "Data Solutions LLC",
    applyLink: "http://datasolutions.com/careers/data-scientist",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d1g",
    reports: [],
    likes: []
  },
  {
    title: "Backend Developer",
    salary: 75000,
    location: "Austin, TX",
    jobType: "Full-time",
    companyName: "Cloud Tech Group",
    applyLink: "http://cloudtech.com/careers/backend-developer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d2h",
    reports: [],
    likes: []
  },
  {
    title: "Marketing Manager",
    salary: 70000,
    location: "Los Angeles, CA",
    jobType: "Part-time",
    companyName: "Marketing Wizards",
    applyLink: "http://marketingwizards.com/careers/marketing-manager",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d8d",
    reports: [],
    likes: []
  },
  {
    title: "UI/UX Designer",
    salary: 65000,
    location: "Seattle, WA",
    jobType: "Full-time",
    companyName: "Design Studios",
    applyLink: "http://designstudios.com/careers/ui-ux-designer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d9e",
    reports: [],
    likes: []
  },
  {
    title: "Project Manager",
    salary: 85000,
    location: "Chicago, IL",
    jobType: "Full-time",
    companyName: "Project Masters",
    applyLink: "http://projectmasters.com/careers/project-manager",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d8d",
    reports: [],
    likes: []
  },
  {
    title: "Systems Analyst",
    salary: 70000,
    location: "Boston, MA",
    jobType: "Internship",
    companyName: "Systems Pros",
    applyLink: "http://systemspros.com/careers/systems-analyst",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d0f",
    reports: [],
    likes: []
  },
  {
    title: "Database Administrator",
    salary: 72000,
    location: "San Diego, CA",
    jobType: "Full-time",
    companyName: "DataWorks Inc.",
    applyLink: "http://dataworks.com/careers/database-administrator",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d1g",
    reports: [],
    likes: []
  },
  {
    title: "DevOps Engineer",
    salary: 78000,
    location: "Denver, CO",
    jobType: "Full-time",
    companyName: "OpsTech Solutions",
    applyLink: "http://opstech.com/careers/devops-engineer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d2h",
    reports: [],
    likes: []
  },
  {
    title: "Content Writer",
    salary: 50000,
    location: "Austin, TX",
    jobType: "Part-time",
    companyName: "Content Creators",
    applyLink: "http://contentcreators.com/careers/content-writer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d8d",
    reports: [],
    likes: []
  },
  {
    title: "Business Analyst",
    salary: 69000,
    location: "Philadelphia, PA",
    jobType: "Full-time",
    companyName: "Analyst Group",
    applyLink: "http://analystgroup.com/careers/business-analyst",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d0f",
    reports: [],
    likes: []
  },
  {
    title: "Software Engineer",
    salary: 85000,
    location: "San Francisco, CA",
    jobType: "Full-time",
    companyName: "CodeWorks",
    applyLink: "http://codeworks.com/careers/software-engineer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d1g",
    reports: [],
    likes: []
  },
  {
    title: "Network Administrator",
    salary: 68000,
    location: "New York, NY",
    jobType: "Full-time",
    companyName: "NetTech Solutions",
    applyLink: "http://nettech.com/careers/network-administrator",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d2h",
    reports: [],
    likes: []
  },
  {
    title: "Graphic Designer",
    salary: 55000,
    location: "Los Angeles, CA",
    jobType: "Part-time",
    companyName: "Creative Studios",
    applyLink: "http://creativestudios.com/careers/graphic-designer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d8d",
    reports: [],
    likes: []
  },
  {
    title: "Product Manager",
    salary: 90000,
    location: "Seattle, WA",
    jobType: "Full-time",
    companyName: "Product Innovators",
    applyLink: "http://productinnovators.com/careers/product-manager",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d9e",
    reports: [],
    likes: []
  },
  {
    title: "Technical Support Specialist",
    salary: 60000,
    location: "Chicago, IL",
    jobType: "Full-time",
    companyName: "TechHelp Solutions",
    applyLink: "http://techhelpsolutions.com/careers/technical-support-specialist",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d8d",
    reports: [],
    likes: []
  },
  {
    title: "Cloud Engineer",
    salary: 82000,
    location: "Boston, MA",
    jobType: "Full-time",
    companyName: "Cloud Experts",
    applyLink: "http://cloudexperts.com/careers/cloud-engineer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d0f",
    reports: [],
    likes: []
  },
  {
    title: "Java Developer",
    salary: 75000,
    location: "San Diego, CA",
    jobType: "Full-time",
    companyName: "JavaTech Inc.",
    applyLink: "http://javatech.com/careers/java-developer",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d1g",
    reports: [],
    likes: []
  },
  {
    title: "Sales Manager",
    salary: 72000,
    location: "Denver, CO",
    jobType: "Full-time",
    companyName: "SalesForce Inc.",
    applyLink: "http://salesforce.com/careers/sales-manager",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d2h",
    reports: [],
    likes: []
  },
  {
    title: "IT Consultant",
    salary: 80000,
    location: "Philadelphia, PA",
    jobType: "Full-time",
    companyName: "ConsultIT",
    applyLink: "http://consultit.com/careers/it-consultant",
    reviews: [],
    owner: "64b27d1f8a8b8d8d8d8d8d8d",
    reports: [],
    likes: []
  },
];
module.exports={data:jobs};
